defaults:
  - server: localhost
  - battle: gen8randombattle
  - reward: dense
  - training: default
  - eval: default
  - algorithm: maskableppo
  - models@ppo: pipeline_ppo    #ppo pour le classique, pipeline_ppo pour la version SOTA
  - models@dqn: dqn
  - wandb: default
  - _self_

resume_path: null

hydra:
  run:
    dir: .
  output_subdir: null
