defaults:
  - server: localhost
  - battle: gen8randombattle_fixed_team
  - reward: dense
  - training: default
  - distributed: default
  - eval: default
  - benchmark: default
  - algorithm: attppo
  - models@ppo: ppo
  - models@dqn: dqn
  - models@attppo: attppo
  - wandb: default
  - _self_

resume_path: null

hydra:
  run:
    dir: .
  output_subdir: null
